<?php

namespace Database\Seeders;

use App\Models\Carer_Level;
use App\Models\Category;
use App\Models\Education_Level;
use App\Models\Experience_Year;
use App\Models\Grade;
use App\Models\Job_Description;
use App\Models\Job_Search_Status;
use App\Models\Job_Study_Field;
use App\Models\Job_Type;
use App\Models\Language;
use App\Models\Skills;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $careerLevel = [
        'Student',
        'Entry Level',
        'Experienced',
        'Manager',
        'Senior Management'
        ];

        foreach ($careerLevel as $item)
        {
            $newCareer = new Carer_Level;
            $newCareer->name = $item;
            $newCareer->save();
        }
        $jobType = [
        'Full Time',
        'Part Time',
        'Freelance/Project',
        'Internship',
        'Shift Based',
        'Work From Home',
        'Volunteering',
        'Student Activity'
        ];

        foreach ($jobType as $item)
        {
            $newJob_Type = new Job_Type;
            $newJob_Type->name = $item;
            $newJob_Type->save();
        }


        $jobTitles = [
        'Accounting apprentice',
        'Actor',
    'Business administration apprentice',
    'School administrator',
    'Financial advisor',
    'Aerospace engineer',
    'Air ambulance doctor',
    'Air ambulance pilot',
    'Aircraft engineer',
    'Alpine ski racer',
    'Ambulance dispatcher',
    'Trainee business analyst',
    'App developer',
    'App co-owner (fitness app)',
    'A&R (artist & repertoire)',
    'Architectural assistant',
    'Architect',
    'Concept artist',
    'Art director',
    'Assistant learning officer',
    'Assistant producer',
    'Assistant producer',
    'Media assistant',
    'Restaurant assistant manager',
    'Audio engineer',
    'Audiologist',
    'Digital engagement apprentice',
    'Events assistant',
    'Barista',
    'Barrister (training)',
    'Barrister',
    'Beekeeper',
    'Biomedical scientist',
    'Bird of prey specialist',
    'Broadcast assistant',
    'Festival build manager',
    'Business administration apprentice',
    "Cake designer",
    "Camera assistant",
    "Camera trainee",
    "Carer",
    "Carpentry",
    "Catchment officer",
    "CEO",
    "Chef",
    "Chemist",
    "Chocolatier",
    "Dancer and choreographer",
    "Civil engineering ",
    "Cleaner",
    'Clinical photographer',
    'Coastguard – maritime operations officer',
    'Coder',
    'Coding events manager',
    'Collections officer',
    'Comedian',
    'Commissioning and development executive',
    'Communications intern',
    'Community education coordinator',
    'Community cohesion officer',
    'Composer',
    'Conservation apprentice',
    'Apprentice conservation officer',
    'Conservation officer',
    'Conservation trainee',
    'Construction manager',
    'Construction site engineer',
    'Senior content executive',
    'Contributor (digital platform)',
    'Membership coordinator in a museum',
    'Copy editor',
    "Coroner's officer",
    'Corporate social responsibility coordinator',
    'Costume designer',
    'Costume standby on Fantastic Beasts',
    'Cosmetics creator',
    'Junior creative',
    'Senior creative',
    'Crèche assistant',
    'Events curator',
    'Customer service team manager',
    'Cyber security apprentice',
    'Dancer',
    'Dance choreographer',
    'Data and compliance manager',
    'Dental lab assistant',
    'Dental nurse assistant',
    'Associate development manager',
    'Costume designer for Fantastic Beasts',
    'Electrical design engineer',
    'Handbag designer',
    'Jewellery designer',
    'Apprentice wing designer',
    'Garden designer',
    'Graphic designer',
    'User experience designer',
    'App developer',
    'Software developer',
    'Business development intern',
    'Development assistant',
    'Development officer',
    'Head of digital and short form',
    'Digital degree apprentice',
    'Digital engagement apprentice',
    'Digital content producer',
    'Digital marketing apprentice',
    'Digital marketing exec',
    'Director in fashion wholesale',
    'Director in photography',
    'Director for sports TV',
    'Director at a music publisher',
    'Director at a gaming company',
    'Studio director',
    'Ambulance dispatcher',
    'Emergency medical dispatcher: call taker',
    'DJ and presenter',
    'DJ producer',
    'Accident and emergency doctor',
    'Air ambulance doctor',
    'Drama facilitator',
    'Festival PR director',
    'Festival programme director',
    'Drone operator',
    'Drummer for Kylie',
    'Civil engineering apprentice',
    'Civil engineering technician',
    'Digital engagement apprentice',
    'Ecologist',
    'Editor',
    'Content editor',
    'Educational support officer',
    'Educational wellbeing specialist',
    'Electrician',
    'Emergency medical dispatcher: call taker',
    'Emergency medical technician',
    'Engagement manager',
    'Acoustic engineer',
    'Aerospace engineer',
    'Aircraft engineer',
    'Audio engineer and musician',
    'Electrical design engineer',
    'Junior simulation engineer',
    'Sound engineer',
    'Tendering engineer',
    'Construction site engineer',
    'Electrical engineer',
    'Engineering ',
    'Engineering technician',
    'Electrical engineer ',
    'Apprentice engineer',
    'Senior system engineer',
    'Structural engineer',
    'Entrepreneur: clothing manufacturer',
    'Ergonomist',
    'Estate agent',
    'Events assistant',
    'Coding events manager',
    'Events curator',
    'Executive assistant',
    'Senior content executive',
    'Farmer',
    'Farming union policy advisor',
    'Farrier',
    'Fashion designer',
    'Festival PR director',
    'Festival programme director',
    'Field technician',
    'Film director',
    'Freelance filmmaker',
    'Filmmaker, sports',
    'Filmmaker and vlogger',
    'Financial advisor',
    'Financial service administrator',
    'Firefighter',
    'Foley artist',
    'Chef and food blogger',
    'Food and drink project planner',
    'Football coach',
    'Front of house usher',
    'Fundraising development officer',
    'Games designer',
    'Gaming company director',
    'Garden designer',
    'Glass-maker',
    'Globemaker',
    'Graphic designer',
    'Graphic designer on Harry Potter',
    'blogger: graphic design',
    'Groundstaff',
    'Hairdresser: for people with additional needs',
    'Hairdresser apprentice',
    'Healthcare assistant',
    'Horse riding instructor',
    'Humanitarian worker',
    'Illustrator',
    'blogger: illustrator',
    'Innovation manager',
    'Intern',
    'Interpretation officer (zookeeper)',
    'IT support analyst',
    'Jewellery maker',
    'Apprentice joiner',
    'Apprentice journalist',
    'Journalist',
    'Karate instructor trainee',
    'Kitchen assistant',
    'Kitchenware maker',
    'Knitwear designer',
    'Landscape assistant',
    'Speech and language therapist',
    'Climate change lawyer',
    'Studio operations lead',
    'Lifeguard',
    'Lighting director',
    'Lighting technician',
    'Locations manager',
    'Machine operator',
    'Make up artist and businesswoman',
    'Makeup business owner',
    'Make up lead: TV',
    'Festival build manager',
    'Coding events manager',
    'Management accountant',
    'Engagement manager',
    'Operations manager',
    "Lewis Capaldi's artist manager",
    'Process optimisation manager',
    'Production manager',
    'Assistant restaurant manager',
    'Sales performance manager',
    'Stage manager',
    'Streaming manager',
    'Managing director ',
    'Marketing manager',
    'Digital marketing ',
    'Digital marketing assistant',
    'Digital marketing specialist',
    'Digital marketing entrepreneur',
    'Digital marketing exec',
    'Marketing intern',
    'Marketing and communications intern',
    'Marketing executive',
    'Marketing manager',
    'Apprentice mechanic',
    'Motorbike mechanic',
    'Mechanical engineer',
    'Media assistant',
    'Assistant media scheduler',
    'Medical student',
    'Medicine management technician',
    'Emergency medical technician',
    'Member of Youth Parliament',
    'Membership coordinator in a museum',
    'Mineral technology apprentice',
    'Model and mental health advocate',
    'Model and business owner',
    'Music business owner and DJ',
    'Music creator',
    'Music director',
    'Music editor',
    'Music festival volunteer',
    'Music manager',
    'Music news reporter',
    'Music playlist editor',
    'Music photographer',
    'Music PR manager',
    'Music promoter',
    'Music supervisor',
    'Musician',
    'Nanny',
    'Naval architect',
    'News editor: online sports',
    'News reporter',
    'Nurse',
    'Critical care nurse',
    'Critical care staff nurse',
    'Mental health nurse',
    'Mental health nurse',
    'Orthopaedic scrub nurse',
    'Nursery worker',
    'Occupational therapy assistant',
    'Occupational therapy technical instructor',
    'Apprentice countryside officer',
    'Assistant learning officer',
    'Online entrepreneur in beauty retail',
    'Studio operations lead',
    'Operations manager',
    'Process optimisation manager',
    'Orthotist',
    'Festival PR director',
    'Festival programme director',
    'Paper maker',
    'Paralegal apprentice',
    'Paramedic',
    'Community specialist paramedic',
    'Party planner',
    'Wedding planner',
    'Patient support and engagement team administrator',
    'Personal trainer',
    'Pet food business owner',
    'Pharmacist',
    'Pharmacologist',
    'Photographer',
    'Physicist',
    'Physiotherapist',
    'Director in photography',
    'Plumber',
    'Poet and writer',
    'Tv Presenter',
    'Press office assistant',
    'Primary teacher',
    'Process optimisation manager',
    'Producer',
    'Associate producer',
    'Producer radio',
    'Producer podcast commissioning',
    'Producer radio and live events',
    'Trainee producer',
    'Production manager',
    'Production management assistant',
    'Production accountant',
    'Production assistant',
    'Product designer',
    'Public relations account assistant',
    'Radio presenter ',
    'Radio producer',
    'Receptionist',
    'Public relations',
    'Cyber security ',
    'Music news reporter',
    'Research scientist and PhD student',
    'Media researcher',
    'Senior researcher',
    'Science student and researcher',
    'Senior research manager',
    'Restaurant assistant manager',
    'Restaurant owner',
    'Laboratory scientist ',
    'Science journalist',
    'Science researcher',
    'Screenwriter',
    'Script editor',
    'Secretary',
    'Social media chef',
    'Software developer',
    'Software engineer',
    'Sound engineer',
    'Speech and language therapist',
    'Sport psychologist',
    'Story editor',
    'Studio director',
    'Supervisor',
    'Talent acquisition manager',
    'Teacher',
    'Teaching assistant',
    'Lighting technician',
    'Emergency medical technician',
    'Medicine management technician',
    'Creative technologist',
    'Minerals technology apprentice',
    'Speech and language therapist',
    'Tour manager',
    'User experience designer',
    'Urgent care desk paramedic',
    'Vet',
    'Veterinary nurse',
    'Veterinary surgeon',
    'Web developer',
    'Wedding dress designer',
    'Woodworker',
    'Writer',
  ];


        foreach ($jobTitles as $item)
        {
            $newJob_Description = new Job_Description;
            $newJob_Description->name = $item;
            $newJob_Description->save();
        }



        $jobCategories = [
        'Accounting/Finance',
        'Administration',
        'Analyst/Research',
        'Banking',
        'Business Development',
        'C-Level Executive/GM/Director',
        'Creative/Design/Art',
        'Customer Service/Support',
        'Education/Teaching',
        'Engineering - Construction/Civil/Architecture',
        'Engineering - Mechanical/Electrical',
        'Engineering - Oil & Gas/Energy',
        'Engineering - Other',
        'Engineering - Telecom/Technology',
        'Fashion',
        'Hospitality/Hotels/Food Services',
        'Human Resources',
        'IT/Software Development',
        'Installation/Maintenance/Repair',
        'Legal',
        'Logistics/Supply Chain',
        'Manufacturing/Production',
        'Marketing/PR/Advertising',
        'Media/Journalism/Publishing',
        'Medical/Healthcare',
        'Operations/Management',
        'Other',
        'Pharmaceutical',
        'Project/Program Management',
        'Purchasing/Procurement',
        'Quality',
        'R&D/Science',
        'Sales/Retail',
        'Sports and Leisure',
        'Strategy/Consulting',
        'Tourism/Travel',
        'Training/Instructor',
        'Writing/Editorial',
    ];


        foreach ($jobCategories as $item)
        {
            $newCategory = new Category;
            $newCategory->name = $item;
            $newCategory->save();
        }



        $jobSearchStatus = [
        'I am unemployed and desperate for a job',
        'I am actively looking for new opportunities and jobs',
        "I am happy where I am but don't mind finding good opportunitles",
        'I am only interested in very specific opportunitles',
        'I am not looking for a job',
    ];


        foreach ($jobSearchStatus as $item)
        {
            $newJob_Search_Status = new Job_Search_Status;
            $newJob_Search_Status->name = $item;
            $newJob_Search_Status->save();
        }




        $experienceDuration = [
        'No experience',
        'Less than 1 year',
        '1 year',
        '2 year',
        '3 years',
        '4 years',
        '5 years',
        '6 years',
        '7 years',
        '8 years',
        '9 years',
        '10 years',
        '11 years',
        '12 years',
        '13 years',
        '14 years',
        '15 years',
        'More than 15 years'
    ];

        foreach ($experienceDuration as $item)
        {
            $newExperience_Year = new Experience_Year;
            $newExperience_Year->name = $item;
            $newExperience_Year->save();
        }


        $educationalLevel = [
        "Bachelor's Degree",
        "Master's degree",
        'Doctorate Degree',
        'High School',
        'Vocational',
        'Diploma'
    ];


        foreach ($educationalLevel as $item)
        {
            $newEducation_Level = new Education_Level;
            $newEducation_Level->name = $item;
            $newEducation_Level->save();
        }


        $languages = [
        'Chinese',
        'Spanish',
        'English',
        'Arabic',
        'Hindi',
        'Bengali',
        'Portuguese',
        'Russian',
        'Japanese',
        'German',
        'Javanese',
        'Lawanda',
        'Telugu',
        'Vietnamese',
        'Marathi',
        'French',
        'Korean',
        'Tamil',
        'Italian',
        'Urdu',
    ];


        foreach ($languages as $item)
        {
            $newLanguage = new Language;
            $newLanguage->name = $item;
            $newLanguage->save();
        }

        $grades = [
        'A/ Excellent / 85 -100%',
        'B/ Very Good / 75 - 85%',
        'C/ Good / 65 - 75%',
        'D/ Fair / 50 - 65%',
        'Not specified'
    ];


        foreach ($grades as $item)
        {
            $newGrade = new Grade;
            $newGrade->name = $item;
            $newGrade->save();
        }



        $skills = [
'design',
'operations',
'technical',
'training',
'sales',
'marketing',
'reporting',
'compliance',
'strategy',
'research',
'analytical',
'engineering',
'policies',
'budget',
'finance',
'project management',
'health',
'customer service',
'documentation',
'content',
'presentation',
'brand',
'presentations',
'safety',
'certification',
'accounting',
'regulations',
'metrics',
'legal',
'engagement',
'database',
'analytics',
'distribution',
'coaching',
'testing',
'vendors',
'consulting',
'writing',
'contracts',
'inventory',
'retail',
'healthcare',
'regulatory',
'scheduling',
'construction',
'logistics',
'mobile',
'C (programming language)',
'correspondence',
'controls',
'human resources',
'specifications',
'recruitment',
'procurement',
'partnership',
'partnerships',
'management experience',
'negotiation',
'hardware',
'programming',
'agile',
'forecasting',
'advertising',
'business development',
'audit',
'architecture',
'supply chain',
'governance',
'staffing',
'continuous improvement',
'product development',
'networking',
'recruiting',
'product management',
'CRM',
'SAP',
'troubleshooting',
'computer science',
'budgeting',
'electrical',
'customer experience',
'I-DEAS',
'economics',
'information technology',
'transportation',
'social media',
'automation',
'lifecycle',
'filing',
'modeling',
'investigation',
'SQL',
'editing',
'purchasing',
'KPIs',
'hospital',
'forecasts',
'acquisition',
'expenses',
'billing',
'change management',
'video',
'invoices',
'administrative support',
'payments',
'lean',
'process improvement',
'installation',
'risk management',
'transactions',
'investigations',
'payroll',
'R (programming language)',
'data analysis',
'statistics',
'coding',
'protocols',
'program management',
'quality assurance',
'windows',
'banking',
'outreach',
'sourcing',
'Microsoft Office',
'merchandising',
'business requirements',
'drawings',
'Salesforce',
'documenting',
'information systems',
'nursing',
'business administration',
'consumers',
'financial services',
'legislation',
'strategic planning',
'MS Office',
'counseling',
'technical support',
'frameworks',
'performance management',
'BI',
'fashion',
'HTML',
'publications',
'internship',
'QA',
'software development',
'oracle',
'Java',
'teaching',
'pharmaceutical',
'ERP',
'fulfillment',
'positioning',
'tax',
'service delivery',
'investigate',
'editorial',
'account management',
'business process',
'valid drivers license',
'electronics',
'PR',
'public relations',
'Javascript',
'assembly',
'digital marketing',
'Linux',
'Facebook',
'spreadsheets',
'recruit',
'proposal',
'SharePoint',
'data entry',
'hotel',
'ordering',
'branding',
'life cycle',
'real estate',
'relationship management',
'researching',
'process improvements',
'chemistry',
'SaaS',
'CAD',
'sales experience',
'mathematics',
'customer-facing',
'audio',
'project management skills',
'six sigma',
'hospitality',
'mechanical engineering',
'auditing',
'employee relations',
'android',
'security clearance',
'licensing',
'Adobe',
'fundraising',
'repairs',
'ISO',
'market research',
'warehouse',
'business strategy',
'PMP',
'data management',
'quality control',
'reconciliation',
'CSS',
'conversion',
'business analysis',
'financial analysis',
'ecommerce',
'business intelligence',
'C++',
'client service',
'publishing',
'supervising',
'complex projects',
'key performance indicators',
'scrum',
'Photoshop',
'sports',
'e-commerce',
'journalism',
'D (programming language)',
'data collection',
'higher education',
'marketing programs',
'financial management',
'business plans',
'user experience',
'client, relationships',
'cloud',
'analyt,ical skills',
'Cisco',
'internal stakehold,ers',
'product marketing',
'regul,atory requirements',
'ITIL',
'informati,on security',
'aviation',
'supply ,chain management',
'Python',
'accounts payable',
'industry, experience',
'AutoCAD',
'purchase orde,rs',
'acq,uisitions',
'TV',
'instrumentation',
'strategic direct,ion',
'law enforcem,ent',
'call center',
'experiments',
'technical skill,s',
'human resource',
'business cases',
'build rela,tionships',
'invoicing',
'support services',
'marketing strategy,',
'operatin,g systems',
'biology',
'start-up',
'electrical, engineering',
'workflow,s',
'routing',
'non-profit',
'marketing plan,s',
'due diligence',
'busines,s management',
'iPhone',
'algorithms',
'architectu,res',
'reconcile',
'dynamic environmen,t',
'external partners,',
'asset managemen,t',
'Micro,soft Word',
'EMEA',
'intra,net',
'SOPs,',
'SAS',
'digital medi,a',
'prospecting',
'financial reporti,ng',
'project delivery',
'SEO',
'operational excellence',
'standard operating procedures',
'C#',
'technical knowledge',
'on-call',
'talent management',
'stakeholder management',
'tablets',
'CMS',
'analyze data',
'financial statements',
'Microsoft Office Suite',
'fitness',
'case management',
'value proposition',
'industry trends',
'RFP',
'broadcast',
'portfolio management',
'fabrication',
'UX',
'financial performance',
'customer requirements',
'psychology',
'marketing materials',
'resource management',
'physics',
'mortgage',
'development activities',
'end user',
'business planning',
'root cause',
'analysis',
'leadership development',
'relationship building',
'SDLC',
'on-boarding',
'quality standards',
'regulatory compliance',
'AWS',
'KPI',
'status reports',
'product line',
'drafting',
'JIRA',
'phone calls',
'product knowledge',
'business stakeholders',
'technical issues',
'admissions',
'supervisory experience',
'usability',
'pharmacy',
'commissioning',
'project plan',
'MS Excel',
'FDA',
'test plans',
'variances',
'UI',
'financing',
'travel arrangements',
'internal customers',
'medical device',
'counsel',
'inventory management',
'performance metrics',
'lighting',
'outsourcing',
'InDesign',
'performance improvement',
'management consulting',
'graphic design',
'transport',
'information management',
'.NET',
'startup',
'matrix',
'front-end',
'project planning',
'business systems',
'accounts receivable',
'public health',
'HRIS',
'German',
'instructional design',
'in-store',
'data center',
'MATLAB',
'employee engagement',
'cost effective',
'sales management',
'API',
'Adobe Creative Suite',
'Twitter',
'program development',
'event planning',
'cash flow',
'strategic plans',
'root cause',
'vendor management',
'trade shows',
'hotels',
'segmentation',
'contract management',
'GIS',
'talent acquisition',
'photography',
'internal communications',
'client services',
'IBM',
'financial reports',
'product quality',
'beverage',
'strong analytical skills',
'underwriting',
'CPR',
'mining',
'sales goals',
'chemicals',
'deposits',
'scripting',
'migration',
'software engineering',
'MIS',
'therapeutic',
'general ledger',
'Tableau',
'MS Project',
'standardization',
'retention',
'spelling',
'media relations',
'OS',
'daily operations',
'immigration',
'product design',
'ETL',
'field sales',
'driving record',
'PeopleSoft',
'benchmark',
'quality management',
'APIs',
'test cases',
'internal controls',
'telecom',
'business issues',
'research projects',
'data quality',
'strategic initiatives',
'office software',
'CFA',
'co-op',
'big data',
'journal entries',
'VMware',
'help desk',
'statistical analysis',
'datasets',
'alliances',
'SolidWorks',
'prototype',
'LAN',
'SCI',
'budget management',
'Unix',
'RFPs',
'Flex',
'GAAP',
'CPG',
'information system',
'customer facing',
'process development',
'web services',
'international',
'travel',
'revenue growth',
'software development life cycle',
'operations management',
'computer applications',
'risk assessments',
'sales operations',
'raw materials',
'internal audit',
'physical security',
'SQL server',
'affiliate',
'computer software',
'manage projects',
'business continuity',
'litigation',
'IT infrastructure',
'cost reduction',
'small business',
'annual budget',
'iOS',
'HTML5',
'real-time',
'consulting experience',
'circuits',
'machine learning',
'risk assessment',
'DNS',
'cross-functional team',
'public policy',
'analyzing data',
'consulting services',

        ];


        foreach ($skills as $item)
        {
            $newSkill = new Skills;
            $newSkill->name = $item;
            $newSkill->save();
        }





        $fields = [
'Agriculture, General',
'Agribusiness Operations',
'Agricultural Business & Management',
'Agricultural Economics',
'Agricultural Mechanization',
'Agricultural Production',
'Agronomy & Crop Science',
'Animal Sciences',
'Food Sciences & Technology',
'Horticulture Operations & Management',
'Horticulture Science',
'Natural Resources Conservation, General',
'Environmental Science',
'Forestry',
'Natural Resources Management',
'Wildlife & Wildlands Management',
'Architecture, General',
'Architectural Environmental Design',
'City/Urban/Regional Planning',
'Interior Architecture',
'Landscape Architecture',
'Area Studies, General (e.g., African, Middle Eastern)',
'Asian Area Studies',
'European Area Studies',
'Latin American Area Studies',
'North American Area Studies',
'Ethnic & Minority Studies, General',
'African American Studies',
'American Indian/Native American Studies',
'Latino/Chicano Studies',
"Women's Studies",
'Liberal Arts & General Studies',
'Library Science',
'Multi/Interdisciplinary Studies',
'Art, General',
'Art History, Criticism & Conservation',
'Fine/Studio Arts',
'Cinema/Film',
'Cinematography/Film/Video Production',
'Dance',
'Design & Visual Communications, General',
'Fashion/Apparel Design',
'Graphic Design',
'Industrial Design',
'Interior Design',
'Music, General',
'Music, Performance',
'Music, Theory & Composition',
'Photography',
'Theatre Arts/Drama',
'Accounting',
'Accounting Technician',
'Business Administration & Management, General',
'Hotel/Motel Management',
'Human Resources Development/Training',
'Human Resources Management',
'International Business Management',
'Labor/Industrial Relations',
'Logistics & Materials Management',
'Marketing Management & Research',
'Office Supervision & Management',
'Operations Management & Supervision',
'Organizational Behavior',
'Purchasing/Procurement/Contracts Management',
'Restaurant/Food Services Management',
'Small Business Management/Operations',
'Travel/Tourism Management',
'Business/Management Quantitative Methods, General',
'Actuarial Science',
'Business/Managerial Economics',
'Finance, General',
'Banking & Financial Support Services',
'Financial Planning & Services',
'Insurance & Risk Management',
'Investments & Securities',
'Management Information Systems',
'Real Estate',
'Sales, Merchandising, & Marketing, General',
'Fashion Merchandising',
'Tourism & Travel Marketing',
'Secretarial Studies & Office Administration',
'Biology, General',
'Biochemistry & Biophysics',
'Cell/Cellular Biology',
'Ecology',
'Genetics',
'Marine/Aquatic Biology',
'Microbiology & Immunology',
'Zoology',
'Physical Sciences, General',
'Astronomy',
'Atmospheric Sciences & Meteorology',
'Chemistry',
'Geological & Earth Sciences',
'Physics',
'Legal Studies, General',
'Court Reporting',
'Law (Pre-Law)',
'Legal Administrative Assisting/Secretarial',
'Paralegal/Legal Assistant',
'Social Sciences, General',
'Anthropology',
'Criminology',
'Economics',
'Geography',
'History',
'International Relations & Affairs',
'Political Science & Government',
'Psychology, Clinical & Counseling',
'Psychology, General',
'Sociology',
'Urban Studies/Urban Affairs',
'Philosophy',
'Religion',
'Theology, General',
'Bible/Biblical Studies',
'Divinity/Ministry',
'Religious Education',
'Aviation & Airway Science, General',
'Aircraft Piloting & Navigation',
'Aviation Management & Operations',
'Construction Trades (e.g., carpentry, plumbing, electrical)',
'Mechanics & Repairers, General',
'Aircraft Mechanics/Technology',
'Autobody Repair/Technology',
'Automotive Mechanics/Technology',
'Avionics Technology',
'Diesel Mechanics/Technology',
'Electrical/Electronics Equip Installation & Repair',
'Heating/Air Conditioner/Refrigeration Install/Repair',
'Precision Production Trades, General',
'Machine Tool Technology',
'Welding Technology',
'Transportation & Materials Moving (e.g., air, ground, & marine)',
'Communications, General',
'Advertising',
'Digital Communications/Media',
'Journalism, Broadcast',
'Journalism, Print',
'Mass Communications',
'Public Relations & Organizational Communication',
'Radio & Television Broadcasting',
'Communications Technology, General',
'Graphic & Printing Equipment Operation',
'Multimedia/Animation/Special Effects',
'Radio & Television Broadcasting Technology',
'Family & Consumer Sciences, General',
'Adult Development & Aging/Gerontology',
'Child Care Services Management',
'Child Development',
'Consumer & Family Economics',
'Food & Nutrition',
'Textile & Apparel',
'Parks, Recreation, & Leisure, General',
'Exercise Science/Physiology/Kinesiology',
'Health & Physical Education/Fitness',
'Parks/Rec/Leisure Facilities Management',
'Sport & Fitness Administration/Management',
'Personal Services, General',
'Cosmetology/Hairstyling',
'Culinary Arts/Chef Training',
'Funeral Services & Mortuary Science',
'Protective Services, General',
'Corrections',
'Criminal Justice',
'Fire Protection & Safety Technology',
'Law Enforcement',
'Military Technologies',
'Public Administration & Services, General',
'Community Organization & Advocacy',
'Public Administration',
'Public Affairs & Public Policy Analysis',
'Social Work',
'Computer & Information Sciences, General',
'Computer Networking/Telecommunications',
'Computer Science & Programming',
'Computer Software & Media Applications',
'Computer System Administration',
'Data Management Technology',
'Information Science',
'Webpage Design',
'Mathematics, General',
'Applied Mathematics',
'Statistics',
'Counseling & Student Services',
'Educational Administration',
'Special Education',
'Teacher Education, General',
'Curriculum & Instruction',
'Early Childhood Education',
'Elementary Education',
'Junior High/Middle School Education',
'Postsecondary Education',
'Secondary Education',
'Teacher Assisting/Aide Education',
'Teacher Education, Subject-Specific',
'Agricultural Education',
'Art Education',
'Business Education',
'Career & Technical Education',
'English-as-a-Second-Language Education',
'English/Language Arts Education',
'Foreign Languages Education',
'Health Education',
'Mathematics Education',
'Music Education',
'Physical Education & Coaching',
'Science Education',
'Social Studies/Sciences Education',
'Engineering (Pre-Engineering), General',
'Aerospace/Aeronautical Engineering',
'Agricultural/Bioengineering',
'Architectural Engineering',
'Biomedical Engineering',
'Chemical Engineering',
'Civil Engineering',
'Computer Engineering',
'Construction Engineering/Management',
'Electrical, Electronics & Communications Engineering',
'Environmental Health Engineering',
'Industrial Engineering',
'Mechanical Engineering',
'Nuclear Engineering',
'Drafting/CAD Technology, General',
'Architectural Drafting/CAD Technology',
'Mechanical Drafting/CAD Technology',
'Engineering Technology, General',
'Aeronautical/Aerospace Engineering Technologies',
'Architectural Engineering Technology',
'Automotive Engineering Technology',
'Civil Engineering Technology',
'Computer Engineering Technology',
'Construction/Building Technology',
'Electrical, Electronics Engineering Technologies',
'Electromechanical/Biomedical Engineering Technologies',
'Environmental Control Technologies',
'Industrial Production Technologies',
'Mechanical Engineering Technology',
'Quality Control & Safety Technologies',
'Surveying Technology',
'English Language & Literature, General',
'American/English Literature',
'Creative Writing',
'Public Speaking',
'Foreign Languages/Literatures, General',
'Asian Languages & Literatures',
'Classical/Ancient Languages & Literatures',
'Comparative Literature',
'French Language & Literature',
'German Language & Literature',
'Linguistics',
'Middle Eastern Languages & Literatures',
'Spanish Language & Literature',
'Health Services Administration, General',
'Hospital/Facilities Administration',
'Medical Office/Secretarial',
'Medical Records',
'Medical/Clinical Assisting, General',
'Dental Assisting',
'Medical Assisting',
'Occupational Therapy Assisting',
'Physical Therapy Assisting',
'Veterinarian Assisting/Technology',
'Chiropractic (Pre-Chiropractic)',
'Dental Hygiene',
'Dentistry (Pre-Dentistry)',
'Emergency Medical Technology',
'Health-Related Professions & Services, General',
'Athletic Training',
'Communication Disorder Services (e.g., Speech Pathology)',
'Public Health',
'Health/Medical Technology, General',
'Medical Laboratory Technology',
'Medical Radiologic Technology',
'Nuclear Medicine Technology',
'Respiratory Therapy Technology',
'Surgical Technology',
'Medicine (Pre-Medicine)',
'Nursing, Practical/Vocational',
'Nursing, Registered',
'Optometry (Pre-Optometry)',
'Osteopathic Medicine',
'Pharmacy (Pre-Pharmacy)',
'Physician Assisting',
'Therapy & Rehabilitation, General',
'Alcohol/Drug Abuse Counseling',
'Massage Therapy',
'Mental Health Counseling',
'Occupational Therapy',
'Physical Therapy (Pre-Physical Therapy)',
'Psychiatric/Mental Health Technician',
'Rehabilitation Therapy',
'Vocational Rehabilitation Counseling',
'Veterinary Medicine (Pre-Veterinarian)',




        ];


        foreach ($fields as $item)
        {
            $test = new Job_Study_Field;
            $test->name = $item;
            $test->save();
        }

    }
}
